### ISSUE TITLE
The lzma-sys/xz submodule returns a 403 error.

### ISSUE THREAD

**Issue by linkmauve** [SonnyX/xdelta-decoder-rust#1]
https://git.tukaani.org/xz.git/ returns a 403 error, it would be nice to point it to an alternative repository.

**Comment by SonnyX** [comment]
It indeed does give a 403 forbidden, however this is the original source of the lzma decompression code.
If you try to go there using your web browser, the following link is valid: https://git.tukaani.org/?p=xz.git;a=summary

**Comment by linkmauve** [comment]
Thanks, I didn’t realise that!
